database.url=jdbc:postgresql://db.txmdfcyckcclvqnpcldn.supabase.co:5432/postgres
database.jdbc-url=jdbc:postgresql://db.txmdfcyckcclvqnpcldn.supabase.co:5432/postgres
database.username=postgres
database.password=Kieumau12!@
database.driver=org.postgresql.Driver

