spring.application.name=cs489

spring.datasource.url=jdbc:postgresql://localhost:5432/cs489-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=schema1
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.graphql.http.path=/graphql
spring.graphql.graphiql.enabled=true
#spring.graphql.graphiql=false
#graphql.graphiql.explorer.enabled=false

spring.graphql.cors.allowed-origins=*

app.jwt.issuer=cs489-lab-7
app.jwt.expiration-seconds=3600
app.jwt.secret=change-me-to-a-very-long-secret-key-32-plus-bytes
