spring.application.name=cs489

spring.datasource.url=jdbc:postgresql://localhost:5432/cs489-project
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.jdbc.dialect=postgresql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=schema1
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
#spring.graphql.graphiql=false
#graphql.graphiql.explorer.enabled=false

spring.graphql.cors.allowed-origins=*
spring.graphql.