DROP SCHEMA IF EXISTS schema1 CASCADE;
CREATE SCHEMA schema1;

CREATE TABLE schema1.patients (
    patient_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL
);

CREATE TABLE schema1.dentists (
    dentist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    email VARCHAR(255) NOT NULL UNIQUE,
    specialization VARCHAR(255)
);

CREATE TABLE schema1.surgeries (
    surgery_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    location_address VARCHAR(255) NOT NULL,
    telephone_number VARCHAR(50) NOT NULL
);

CREATE TABLE schema1.addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL UNIQUE,
    mailing_address VARCHAR(500) NOT NULL,
    city VARCHAR(255) NOT NULL,
    CONSTRAINT fk_addresses_patient
        FOREIGN KEY (patient_id)
        REFERENCES schema1.patients (patient_id)
        ON DELETE CASCADE
);

CREATE TABLE schema1.appointments (
    appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_date_time TIMESTAMP NOT NULL,
    dentist_id BIGINT NOT NULL,
    patient_id BIGINT NOT NULL,
    surgery_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    CONSTRAINT fk_appointments_dentist
        FOREIGN KEY (dentist_id)
        REFERENCES schema1.dentists (dentist_id),
    CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id)
        REFERENCES schema1.patients (patient_id),
    CONSTRAINT fk_appointments_surgery
        FOREIGN KEY (surgery_id)
        REFERENCES schema1.surgeries (surgery_id)
);

CREATE TABLE schema1.bills (
    bill_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(10,2) NOT NULL,
    paid BOOLEAN NOT NULL,
    patient_id BIGINT NOT NULL,
    CONSTRAINT fk_bills_patient
        FOREIGN KEY (patient_id)
        REFERENCES schema1.patients (patient_id)
        ON DELETE CASCADE
);

CREATE TABLE schema1.roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE schema1.users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE schema1.user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES schema1.users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES schema1.roles (role_id)
        ON DELETE CASCADE
);

